coverage:
  status:
    project:
      default:
        target: auto
      dash-num:
        flags: [dash-num]
        target: auto
      dash-script:
        flags: [dash-script]
        target: auto
      dash-pow:
        flags: [dash-pow]
        target: auto
      dash-pkc:
        flags: [dash-pkc]
        target: auto
      dash-primitives:
        flags: [dash-primitives]
        target: auto
      dash-params:
        flags: [dash-params]
        target: auto
      dash-p2p-core:
        flags: [dash-p2p-core]
        target: auto
    patch:
      default:
        target: auto
      dash-num:
        flags: [dash-num]
        target: auto
      dash-script:
        flags: [dash-script]
        target: auto
      dash-pow:
        flags: [dash-pow]
        target: auto
      dash-pkc:
        flags: [dash-pkc]
        target: auto
      dash-primitives:
        flags: [dash-primitives]
        target: auto
      dash-params:
        flags: [dash-params]
        target: auto
      dash-p2p-core:
        flags: [dash-p2p-core]
        target: auto

flags:
  dash-num:
    paths: [pkgs/num/]
    carryforward: true
  dash-script:
    paths: [pkgs/script/]
    carryforward: true
  dash-pow:
    paths: [pkgs/pow/]
    carryforward: true
  dash-pkc:
    paths: [pkgs/pkc/]
    carryforward: true
  dash-primitives:
    paths: [pkgs/primitives/]
    carryforward: true
  dash-params:
    paths: [pkgs/params/]
    carryforward: true
  dash-p2p-core:
    paths: [pkgs/p2p_core/]
    carryforward: true
