[graph]
all-features = true

[advisories]
yanked = "deny"

[bans]
deny = [
  { crate = "hex-literal", reason = "use `hex_conservative` instead" },
]
multiple-versions = "warn"

[licenses]
allow = [
  "Apache-2.0",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "BSL-1.0",
  "CC0-1.0",
  "ISC",
  "MIT",
  "Unicode-3.0",
  "Unlicense",
]
