[package]
name = "dash-sample-parser"
version = "0.0.0"
edition = "2021"
license = "MIT"
publish = false

[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[lib]
name = "demo_parser"
path = "parser.rs"
crate-type = ["cdylib"]

[features]
default = []
std = []
full = ["std"]

[dependencies]
dash-primitives = { version = "0.0.0", path = "../../../pkgs/primitives", default-features = false, features = [
  "serde",
] }
dash-types = { version = "0.0.0", path = "../../../pkgs/types", default-features = false }
hex-conservative = { version = "0.3", default-features = false, features = [
  "alloc",
] }
serde_json = { version = "1", default-features = false, features = ["alloc"] }
wasm-bindgen = "0.2"

[lints]
workspace = true
