//
// Copyright (c) 2026-present, The Dash Core developers
// SPDX-License-Identifier: MIT
// See the accompanying file LICENSE or https://opensource.org/license/MIT
//

//! Keccak-f[1600] constants.
//!
//! Round constants are generated by the LFSR defined in FIPS 202 Algorithm 1.
//! Rotation offsets follow Algorithm 2 (Section 3.2.2).

/// Single-bit output of the LFSR (FIPS 202, Algorithm 1).
///
/// The polynomial is x^8 + x^6 + x^5 + x^4 + 1 over GF(2).
const fn rc(t: usize) -> bool {
  let t = t % 255;
  if t == 0 {
    return true;
  }
  // R is an 8-bit register, MSB-first: R[0] is bit 7 of the byte.
  // Initial value: R = 10000000_2 = 0x80.
  let mut r: u8 = 0x80;
  let mut i = 0;
  while i < t {
    // Step a: prepend a 0 bit (shift right), capturing the overflow.
    let overflow = r & 1; // R[8] = old R[7]
    r >>= 1;
    // Steps b-e: XOR R[0], R[4], R[5], R[6] with the overflow bit.
    // R[0]=bit7, R[4]=bit3, R[5]=bit2, R[6]=bit1 -> mask 0x8E.
    r ^= overflow.wrapping_mul(0x8E);
    i += 1;
  }
  (r >> 7) & 1 == 1
}

/// Sponge rate in bytes (576 bits / 8).
pub(crate) const RATE: usize = 72;

/// 24 round constants for Keccak-f[1600] (FIPS 202, Algorithm 5).
///
/// Each RC[ir] has bits set only at positions 2^j - 1 for j in 0..=6, i.e. at
/// bit indices {0, 1, 3, 7, 15, 31, 63}.
pub(crate) const RC: [u64; 24] = {
  let mut out = [0u64; 24];
  let mut ir = 0;
  while ir < 24 {
    let mut val = 0u64;
    let mut j = 0u32;
    while j <= 6 {
      if rc(j as usize + 7 * ir) {
        val |= 1u64 << ((1u32 << j) - 1);
      }
      j += 1;
    }
    out[ir] = val;
    ir += 1;
  }
  out
};

/// Rotation offsets for each lane (x, y) (FIPS 202, Section 3.2.2).
///
/// Indexed as `ROTC[x + 5 * y]` to match the flat state layout.
pub(crate) const ROTC: [u32; 25] = {
  let mut out = [0u32; 25];
  // Lane (0, 0) has offset 0 (already set).
  let (mut x, mut y) = (1usize, 0usize);
  let mut t = 0usize;
  while t < 24 {
    out[x + 5 * y] = (((t + 1) * (t + 2)) / 2 % 64) as u32;
    let nx = y;
    let ny = (2 * x + 3 * y) % 5;
    x = nx;
    y = ny;
    t += 1;
  }
  out
};

#[cfg(test)]
mod tests {
  use super::*;

  /// Round constants may only have bits at positions 2^j - 1.
  #[test]
  fn check_rc_bitpos() {
    let mask: u64 = (1 << 0) | (1 << 1) | (1 << 3) | (1 << 7) | (1 << 15) | (1 << 31) | (1 << 63);
    for &c in &RC {
      assert_eq!(c & !mask, 0, "RC {c:#018x} has bits outside valid positions");
    }
  }

  /// Known-good values taken from sphlib
  #[test]
  fn spot_check_rc() {
    #[rustfmt::skip]
    let expected: [u64; 24] = [
      0x0000000000000001, 0x0000000000008082,
      0x800000000000808a, 0x8000000080008000,
      0x000000000000808b, 0x0000000080000001,
      0x8000000080008081, 0x8000000000008009,
      0x000000000000008a, 0x0000000000000088,
      0x0000000080008009, 0x000000008000000a,
      0x000000008000808b, 0x800000000000008b,
      0x8000000000008089, 0x8000000000008003,
      0x8000000000008002, 0x8000000000000080,
      0x000000000000800a, 0x800000008000000a,
      0x8000000080008081, 0x8000000000008080,
      0x0000000080000001, 0x8000000080008008,
    ];
    assert_eq!(RC, expected);
  }

  /// Known-good values taken from sphlib
  #[test]
  fn spot_check_rotc() {
    // Indexed as ROTC[x + 5*y]. Each row below is y=const, x=0..4.
    #[rustfmt::skip]
    let expected: [u32; 25] = [
      //  x=0  x=1  x=2  x=3  x=4
          0,   1,  62,  28,  27,  // y=0
         36,  44,   6,  55,  20,  // y=1
          3,  10,  43,  25,  39,  // y=2
         41,  45,  15,  21,   8,  // y=3
         18,   2,  61,  56,  14,  // y=4
    ];
    assert_eq!(ROTC, expected);
  }
}
