/**
 * Copyright (c) 2026-present, The Dash Core developers
 * SPDX-License-Identifier: MIT
 * See the accompanying file LICENSE or https://opensource.org/license/MIT
 *
 * @description Common predicates for filtering types by context.
 */

import lib.files
import rust

/** Materialises function spans per file for containment checks. */
pragma[nomagic]
private predicate functionSpan(File file, int fStart, int fEnd) {
  exists(Function f | file = fileOf(f) and fStart = startLine(f) and fEnd = endLine(f))
}

/** Holds if `t` is defined inside a function body rather than at module level. */
predicate isLocalType(TypeItem t) {
  exists(File file, int fStart, int fEnd |
    functionSpan(file, fStart, fEnd) and
    file = fileOf(t) and
    startLine(t) > fStart and
    endLine(t) <= fEnd
  )
}

/** Holds if `t` was generated by a macro expansion. */
predicate isMacroGenerated(TypeItem t) { exists(MacroItems m | t = m.getItem(_)) }

/** Materialises test module spans per file. */
pragma[nomagic]
private predicate testModuleSpan(File file, int mStart, int mEnd) {
  exists(Module m |
    file = fileOf(m) and
    mStart = startLine(m) and
    mEnd = endLine(m) and
    m.getName().getText() = "tests" and
    m.getAnAttr().getMeta().getPath().getSegment().getIdentifier().getText() = "cfg"
  )
}

/** Holds if `t` is inside a test module or test file. */
predicate isTestCode(TypeItem t) {
  fileOf(t).getAbsolutePath().matches("%/tests/%")
  or
  exists(File file, int mStart, int mEnd |
    testModuleSpan(file, mStart, mEnd) and
    file = fileOf(t) and
    startLine(t) > mStart and
    endLine(t) <= mEnd
  )
}

/** Holds if `t` is a source type eligible for any check. */
predicate isSourceType(TypeItem t) {
  (t instanceof Struct or t instanceof Enum or t instanceof Union) and
  fileOf(t).fromSource() and
  not isTestCode(t) and
  not isMacroGenerated(t) and
  not isLocalType(t)
}

/** Holds if struct `s` has exactly one unnamed (tuple) field. */
predicate isSingleTupleField(Struct s) { count(s.getFieldList().(TupleFieldList).getField(_)) = 1 }

/** Gets the crate directory prefix for a source type. */
string cratePrefix(TypeItem t) {
  exists(string path |
    path = fileOf(t).getAbsolutePath() and
    result = path.regexpCapture("(.*/pkgs/[^/]+/).*", 1)
  )
}

/** Gets the type name of a field in struct `s`. */
string structFieldTypeName(Struct s) {
  exists(PathTypeRepr tr |
    tr = s.getFieldList().(StructFieldList).getAField().getTypeRepr() or
    tr = s.getFieldList().(TupleFieldList).getField(_).getTypeRepr()
  |
    result = tr.getPath().getSegment().getIdentifier().getText()
  )
}

/** Gets the type name of a field in enum variant of `e`. */
string enumFieldTypeName(Enum e) {
  exists(Variant v, PathTypeRepr tr |
    v = e.getVariantList().getAVariant() and
    (
      tr = v.getFieldList().(StructFieldList).getAField().getTypeRepr() or
      tr = v.getFieldList().(TupleFieldList).getField(_).getTypeRepr()
    )
  |
    result = tr.getPath().getSegment().getIdentifier().getText()
  )
}

/** Gets the type name of a field in type item `t` (struct or enum). */
string typeFieldName(TypeItem t) {
  result = structFieldTypeName(t)
  or
  result = enumFieldTypeName(t)
}
