name: Comment on PRs

on:
  pull_request_target:
    types: [synchronize, opened, reopened, closed]
  schedule:
    - cron: "0 6 * * 1"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  comment:
    name: Comment on pull requests
    runs-on: ubuntu-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Read environment
        run: cat .github/ci.env >> "$GITHUB_ENV"

      - name: Update PR comments
        uses: actions/github-script@v8
        with:
          script: |
            const script = require("./.github/scripts/pr_comment.js");
            await script({ github, context });
